### ISSUE TITLE
Missing Functions

### ISSUE THREAD

**Issue by akamicah** [sbarisic/Squirrel.NET#1]
The following functions have been identified as missing;

sq_setnativeclosurename(..);
sq_getnativeclosurename(..);   <-  Reference ObjectCreation.cpp Line 196

**Comment by sbarisic** [comment]
About sq_getnativeclosurename in ObjectCreation.cpp, i actually mistyped that. It should have been sq_setnativeclosurename. I implemented that one, but i can't find sq_getnativeclosurename anywhere in the source.

**Comment by akamicah** [comment]
Excellent news. Thank you!
